name: Deploy on Prod Env

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node v16.x
        uses: actions/setup-node@v1
        with:
          node-version: 'v16.x'
      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm install -g @angular/cli
          npm install --force
          ng build --configuration production
          
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: 13.235.0.128
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: "Authoritti-FE-prod/"
          
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 13.235.0.128
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl restart nginx 
